diktat-maven-plugin
### What's done:
* Fixes

diff --git a/.github/workflows/diktat_snapshot.yml b/.github/workflows/diktat_snapshot.yml
--- a/.github/workflows/diktat_snapshot.yml
+++ b/.github/workflows/diktat_snapshot.yml
@@ -41,4 +41,7 @@ jobs:
           mvn -B versions:set -DnewVersion=${{ env.BASE_VERSION }}-SNAPSHOT
           mvn -B versions:set-property -Dproperty=diktat-check.version -DnewVersion=${{ env.BASE_VERSION }}-pre
       - name: Run diktat snapshot via ktlint
-        run: mvn diktat:check@diktat
+        run: |
+          mvn -B diktat:check@diktat --pl diktat-common || echo "LintErrors encountered"
+          mvn -B diktat:check@diktat --pl diktat-test-framework || echo "LintErrors encountered"
+          mvn -B diktat:check@diktat --pl diktat-rules
